apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "aws-ec2-security-group.labels" . | nindent 4 }}
spec:
  terraformVersion: {{ .Values.terraform.version }}
  terraformRunnerPullPolicy: IfNotPresent
  terraformModule: {{ .Values.terraform.module }}?ref={{ .Values.terraform.moduleVersion }}
  resourceDownloads:
  - address: https://github.com/appvia/terraform-providers.git//aws/aws.tf?ref=main
  ignoreDelete: false
  {{- with .Values.aws.credentials }}
  credentials:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  env:
  - name: TF_VAR_region
    value: {{ required "You must specify an AWS region!" .Values.aws.region }}
  - name: TF_VAR_name
    value: {{ required "You must specify a EC2-VPC security group name!" .Values.ec2.sg_name }}
  - name: TF_VAR_vpc_id
    value: {{ required "You must specify a VPC ID!" .Values.ec2.vpc_id }}
  - name: TF_VAR_ingress_with_cidr_blocks
    value: {{ .Values.ec2.ingress_with_cidr_blocks | toJson }}
  outputsSecret: "{{ .Chart.Name }}-outputs"
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "{{ .Chart.Name }}"
        in_cluster_config  = true
        namespace = "{{ .Release.Namespace }}"
      }
    }
